version: '3.8'

services:
  webapp:
    image: jonasdenadai/ror:3.1.2-3.16-7.0.4
    
    ports:
      - "3000:3000"
    
    volumes:
      - ".:/app" 
  
    networks:
      - minha-rede

    command: rails new . -f

    command: rails s -p "3000" -b "0.0.0.0"

networks:
  minha-rede:
    driver: bridge
