version: '3.8'

services:
  webapp:
    image: ror:1.2
    
    ports:
      - "3000:3000"
    
    volumes:
      - ".:/app" 

    command: cd app_padrao
    command: bundle exec rails s -p "3000" -b "0.0.0.0"
  
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
